FROM node:20-alpine AS base

# Install dependencies only when needed
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the lockfile
COPY package.json yarn.lock* ./
RUN yarn --frozen-lockfile --network-concurrency 8 --network-timeout 300000

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED=1

# Build arguments for Next.js build-time variables
ARG NEXT_PUBLIC_API_URL=http://localhost:3000/api
ARG BACKEND_URL=http://bs-commerce-backend:3000
ARG NEXT_PUBLIC_STOREFRONT_URL=http://localhost:3001
ARG NEXT_PUBLIC_AUTH_REQUIRED_IDENTIFIER=either
ARG NEXT_PUBLIC_MULTIVENDOR_ENABLED=false
ARG NEXT_PUBLIC_GUEST_CHECKOUT_ENABLED=true
ARG NEXT_PUBLIC_SOCIAL_LOGIN_ENABLED=true
ARG NEXT_PUBLIC_REVIEWS_ENABLED=true
ARG NEXT_PUBLIC_DEFAULT_LOCALE=en
ARG NEXT_PUBLIC_SUPPORTED_LOCALES=en,bn
ARG NEXT_PUBLIC_DEFAULT_CURRENCY=USD
ARG NEXT_PUBLIC_SUPPORTED_CURRENCIES=USD,BDT
ARG NEXT_PUBLIC_MULTI_STORE_ENABLED=false
ARG NEXT_PUBLIC_GEOGRAPHY_ENABLED=false
ARG NEXT_PUBLIC_SINGLE_STORE_CART=false
ARG NEXT_PUBLIC_GEO_LOCATION_TIER_FILTER=served_and_extended
ARG NEXT_PUBLIC_GEO_LIST_ONLY_SERVED=true

ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV BACKEND_URL=$BACKEND_URL
ENV NEXT_PUBLIC_STOREFRONT_URL=$NEXT_PUBLIC_STOREFRONT_URL
ENV NEXT_PUBLIC_AUTH_REQUIRED_IDENTIFIER=$NEXT_PUBLIC_AUTH_REQUIRED_IDENTIFIER
ENV NEXT_PUBLIC_MULTIVENDOR_ENABLED=$NEXT_PUBLIC_MULTIVENDOR_ENABLED
ENV NEXT_PUBLIC_GUEST_CHECKOUT_ENABLED=$NEXT_PUBLIC_GUEST_CHECKOUT_ENABLED
ENV NEXT_PUBLIC_SOCIAL_LOGIN_ENABLED=$NEXT_PUBLIC_SOCIAL_LOGIN_ENABLED
ENV NEXT_PUBLIC_REVIEWS_ENABLED=$NEXT_PUBLIC_REVIEWS_ENABLED
ENV NEXT_PUBLIC_DEFAULT_LOCALE=$NEXT_PUBLIC_DEFAULT_LOCALE
ENV NEXT_PUBLIC_SUPPORTED_LOCALES=$NEXT_PUBLIC_SUPPORTED_LOCALES
ENV NEXT_PUBLIC_DEFAULT_CURRENCY=$NEXT_PUBLIC_DEFAULT_CURRENCY
ENV NEXT_PUBLIC_SUPPORTED_CURRENCIES=$NEXT_PUBLIC_SUPPORTED_CURRENCIES
ENV NEXT_PUBLIC_MULTI_STORE_ENABLED=$NEXT_PUBLIC_MULTI_STORE_ENABLED
ENV NEXT_PUBLIC_GEOGRAPHY_ENABLED=$NEXT_PUBLIC_GEOGRAPHY_ENABLED
ENV NEXT_PUBLIC_SINGLE_STORE_CART=$NEXT_PUBLIC_SINGLE_STORE_CART
ENV NEXT_PUBLIC_GEO_LOCATION_TIER_FILTER=$NEXT_PUBLIC_GEO_LOCATION_TIER_FILTER
ENV NEXT_PUBLIC_GEO_LIST_ONLY_SERVED=$NEXT_PUBLIC_GEO_LIST_ONLY_SERVED

RUN yarn build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3001
ENV HOSTNAME="0.0.0.0"

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3001

CMD ["node", "server.js"]
